# Generated by Django 3.1.3 on 2021-07-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('PROFESSOR', 'PROFESSOR')], max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_type', 'mobile'), ('user_type', 'email')},
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('std', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100)),
                ('caste', models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('OTHER', 'OTHER')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('specilization', models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('OTHER', 'OTHER')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('professor_specilization', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.usermodel')),
            ],
        ),
    ]
